### ISSUE TITLE
Wavespectra Plotting

### ISSUE THREAD

**Issue by maheshreshwa** [wavespectra/wavespectra#57]
Dear Rafael Guedes,
This is Mahesh R from India. First I am thankful to you for developing such a python module to explore wave spectra. For the past one week, I have been practicing wavespectra module. However i am getting AttributeError which i couldnt fix it.

Code and output as follows, Kindly help me out.
thanks in advance.
*****************************************************
import matplotlib.pyplot as plt
import cmocean
from wavespectra import read_era5

dset = read_era5(
    "/WINDOWS/Mahesh R/Python/Wave Data Analysis/wavespectra-master/docs/_static/era5file.nc").isel(time=0)
ds = dset.isel(lat=0, lon=0)
ds.spec.plot()
plt.show()

**Output**
[Running] /home/arun/anaconda3/bin/python -u "/WINDOWS/Mahesh R/Python/Wave Data Analysis/ws_plotting types.py"
Traceback (most recent call last):
  File "/WINDOWS/Mahesh R/Python/Wave Data Analysis/ws_plotting types.py", line 9, in <module>
    ds.spec.plot()
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/specarray.py", line 756, in plot
    return polar_plot(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/plot.py", line 350, in polar_plot
    return wp()
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/plot.py", line 116, in __call__
    axes = [pobj.axes]
AttributeError: 'QuadContourSet' object has no attribute 'axes'
******************************************************

**Comment by maheshreshwa** [comment]
Dear @rafa-guedes,
   I am facing a new problem now. Kindly help me. The code and error reports are follows,

import matplotlib.pyplot as plt
import cmocean
from wavespectra import read_era5
import numpy as np

dset = read_era5(
    "/WINDOWS/Mahesh R/Python/Wave Data Analysis/wavespectra-master/docs/_static/era5file.nc"
)
ds = dset.isel(lat=0, lon=0, time=0)

# Faceting
dset.spec.plot(
    col="lon",
    row="lat",
    figsize=(16, 8),
    add_colorbar=False,
    show_theta_labels=False,
    show_radii_labels=True,
    radii_ticks=[0.05, 0.1, 0.2, 0.4],
    rmax=0.4,
    radii_labels_size=5,
    cmap="Spectral_r",
)

Output:

(base) arun@cee-harsha:/WINDOWS/Mahesh R/Python/Wave Data Analysis$  /usr/bin/env /home/arun/anaconda3/bin/python /home/arun/.vscode/extensions/ms-python.python-2021.10.1336267007/pythonFiles/lib/python/debugpy/launcher 39005 -- "/WINDOWS/Mahesh R/Python/Wave Data Analysis/ws_plotting types.py" 
Traceback (most recent call last):
  File "/WINDOWS/Mahesh R/Python/Wave Data Analysis/ws_plotting types.py", line 85, in <module>
    dset.spec.plot(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/specarray.py", line 756, in plot
    return polar_plot(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/plot.py", line 350, in polar_plot
    return wp()
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/plot.py", line 107, in __call__
    pobj = getattr(self.darr.plot, self.kind)(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/plot.py", line 1308, in plotmethod
    return newplotfunc(**allargs)
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/plot.py", line 1112, in newplotfunc
    return _easy_facetgrid(darray, kind="dataarray", **allargs)
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/facetgrid.py", line 689, in _easy_facetgrid
    return g.map_dataarray(plotfunc, x, y, **kwargs)
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/facetgrid.py", line 285, in map_dataarray
    mappable = func(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/plot.py", line 1169, in newplotfunc
    darray = darray.transpose(*dims, transpose_coords=True)
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/core/dataarray.py", line 2289, in transpose
    dims = tuple(utils.infix_dims(dims, self.dims, missing_dims))
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/core/utils.py", line 794, in infix_dims
    raise ValueError(
ValueError: ('freq', 'dir') must be a permuted list of ('time', 'freq', 'dir'), unless `...` is included

**Comment by rafa-guedes** [comment]
Hi @maheshreshwa, good that upgrading matplotlib fixed your issue. Could you please send what matplotlib version you had before? just so I can add a minimum version to the requirements.

Your second problem is because you are using `dset` to plot it but you are not specifying `col` / `row` arguments. Your code will work if you use `ds` instead of `dset`, which is sliced at one single position and time, or specify `col` / `row` and other appropriate paramteres to plot multiple spectra. Have a look at the [xarray](http://xarray.pydata.org/en/stable/user-guide/plotting.html#faceting) documentation on faceting - wavespectra plotting is defined as a wrapper around xarray.

**Comment by maheshreshwa** [comment]
Dear @rafa-guedes, Thank you. The older version of matplotlib that i used, was 2.2.1. Regarding the faceting problem I tried with ds option instead of dset. But still there is some value error. Kindly see the error report

import matplotlib.pyplot as plt
import cmocean
from wavespectra import read_era5
import numpy as np

dset = read_era5("/WINDOWS/Mahesh R/Python/Wave Data Analysis/wavespectra-master/docs/_static/era5file.nc")
ds = dset.isel(lat=0, lon=0, time=0)

# Faceting
ds.spec.plot(
    col="lon",
    row="lat",
    figsize=(16, 8),
    add_colorbar=False,
    show_theta_labels=False,
    show_radii_labels=True,
    radii_ticks=[0.05, 0.1, 0.2, 0.4],
    rmax=0.4,
    radii_labels_size=5,
    cmap="Spectral_r",
)
ptl.show()

#Output

File "/WINDOWS/Mahesh R/Python/Wave Data Analysis/ws_plotting types.py", line 85, in <module>
    ds.spec.plot(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/specarray.py", line 756, in plot
    return polar_plot(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/plot.py", line 350, in polar_plot
    return wp()
  File "/home/arun/anaconda3/lib/python3.8/site-packages/wavespectra/plot.py", line 107, in __call__
    pobj = getattr(self.darr.plot, self.kind)(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/plot.py", line 1308, in plotmethod
    return newplotfunc(**allargs)
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/plot.py", line 1112, in newplotfunc
    return _easy_facetgrid(darray, kind="dataarray", **allargs)
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/facetgrid.py", line 672, in _easy_facetgrid
    g = FacetGrid(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/plot/facetgrid.py", line 122, in __init__
    rep_col = col is not None and not data[col].to_index().is_unique
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/core/dataarray.py", line 692, in to_index
    return self.variable.to_index()
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/core/variable.py", line 546, in to_index
    return self.to_index_variable().to_index()
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/core/variable.py", line 533, in to_index_variable
    return IndexVariable(
  File "/home/arun/anaconda3/lib/python3.8/site-packages/xarray/core/variable.py", line 2571, in __init__
    raise ValueError(f"{type(self).__name__} objects must be 1-dimensional")
ValueError: IndexVariable objects must be 1-dimensional
